export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  CHANGE_PASSWORD: '/change-password',

  USERS: '/users',
  USERS_CREATE: '/users/create',
  USERS_SEARCH: '/users/search',
  USERS_DETAIL: '/users/detail',
  USERS_EDIT: '/users/edit',
  USERS_TOGGLE: '/users/toggle',
  USERS_UNLOCK: '/users/unlock',
  USERS_RESET_LOGIN: '/users/reset-login',

  PERSONS: '/persons',
  PERSONS_SEARCH: '/persons/search',
  PERSONS_CREATE: '/persons/create',
  PERSONS_DETAIL: '/persons/detail',
  PERSONS_EDIT: '/persons/edit',
  PERSONS_ADDRESSES: '/persons/addresses',
  PERSONS_DEMOGRAPHICS: '/persons/demographics',
  PERSONS_EMERGENCY: '/persons/emergency-contacts',
  PERSONS_BULK_LOAD: '/persons/bulk-load',

  ADDRESSES: '/persons/addresses',
  ADDRESSES_SEARCH: '/persons/addresses/search',
  ADDRESSES_CREATE: '/persons/addresses/create',
  ADDRESSES_DETAIL: '/persons/addresses/detail',
  ADDRESSES_EDIT: '/persons/addresses/edit',
  ADDRESSES_BULK_LOAD: '/persons/addresses/bulk-load',

  DEMOGRAPHICS: '/persons/demographics',
  DEMOGRAPHICS_SEARCH: '/persons/demographics/search',
  DEMOGRAPHICS_CREATE: '/persons/demographics/create',
  DEMOGRAPHICS_DETAIL: '/persons/demographics/detail',
  DEMOGRAPHICS_EDIT: '/persons/demographics/edit',
  DEMOGRAPHICS_BULK_LOAD: '/persons/demographics/bulk-load',

  STUDENTS_ADMISSION: '/students/admission',
  STUDENTS_ENROLLMENT: '/students/enrollment',
  STUDENTS_GRADES: '/students/grades',

  CATALOGS_ZIP_CODES: '/zip-codes',
  CATALOGS_ZIP_CODES_CREATE: '/zip-codes/create',
  CATALOGS_CLASSES: '/classes',
} as const;
